name: live_cache
description: "A cache that comes in handy for an offline-first setup."
version: 0.2.0
repository: https://github.com/martinsellergren/live_cache

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  test: ^1.25.8

dependencies:
  meta: ^1.15.0
  collection: ^1.18.0
  rxdart: ^0.28.0
