name: live_cache
description: "A cache that comes in handy for an offline-first setup."
version: 0.2.0
repository: https://github.com/martinsellergren/live_cache

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  flutter_lints: ^4.0.0

dependencies:
  meta: ^1.15.0
  collection: ^1.18.0
  rxdart: ^0.28.0
